package prose

func wordyPhraseRules() []Rule {
	return []Rule{
		newRule("due-to-the-fact-that-capitalized", `\bDue to the fact that\b`, "Because"),
		newRule("due-to-the-fact-that", `\bdue to the fact that\b`, "because"),
		newRule("in-the-event-that-capitalized", `\bIn the event that\b`, "If"),
		newRule("in-the-event-that", `\bin the event that\b`, "if"),
		newRule("for-the-purpose-of-capitalized", `\bFor the purpose of\b`, "For"),
		newRule("for-the-purpose-of", `\bfor the purpose of\b`, "for"),
		newRule("whether-or-not-capitalized", `\bWhether or not\b`, "Whether"),
		newRule("whether-or-not", `\bwhether or not\b`, "whether"),
		newRule("has-the-ability-to-capitalized", `\bHas the ability to\b`, "Can"),
		newRule("has-the-ability-to", `\bhas the ability to\b`, "can"),
		newRule("has-the-capability-to-capitalized", `\bHas the capability to\b`, "Can"),
		newRule("has-the-capability-to", `\bhas the capability to\b`, "can"),
		newRule("is-able-to-capitalized", `\bIs able to\b`, "Can"),
		newRule("is-able-to", `\bis able to\b`, "can"),
		newRule("are-able-to-capitalized", `\bAre able to\b`, "Can"),
		newRule("are-able-to", `\bare able to\b`, "can"),
		newRule("a-number-of-capitalized", `\bA number of\b`, "Many"),
		newRule("a-number-of", `\ba number of\b`, "many"),
		newRule("at-this-point-in-time-capitalized", `\bAt this point in time\b`, "Now"),
		newRule("at-this-point-in-time", `\bat this point in time\b`, "now"),
		newRule("in-a-timely-manner-capitalized", `\bIn a timely manner\b`, "Promptly"),
		newRule("in-a-timely-manner", `\bin a timely manner\b`, "promptly"),
		newRule("in-close-proximity-to-capitalized", `\bIn close proximity to\b`, "Near"),
		newRule("in-close-proximity-to", `\bin close proximity to\b`, "near"),
		newRule("in-accordance-with-capitalized", `\bIn accordance with\b`, "Under"),
		newRule("in-accordance-with", `\bin accordance with\b`, "under"),
		newRule("in-relation-to-capitalized", `\bIn relation to\b`, "About"),
		newRule("in-relation-to", `\bin relation to\b`, "about"),
		newRule("on-the-basis-of-capitalized", `\bOn the basis of\b`, "From"),
		newRule("on-the-basis-of", `\bon the basis of\b`, "from"),
		newRule("prior-to-capitalized", `\bPrior to\b`, "Before"),
		newRule("prior-to", `\bprior to\b`, "before"),
		newRule("subsequent-to-capitalized", `\bSubsequent to\b`, "After"),
		newRule("subsequent-to", `\bsubsequent to\b`, "after"),
		newRule("with-regard-to-capitalized", `\bWith regard to\b`, "About"),
		newRule("with-regard-to", `\bwith regard to\b`, "about"),
		newRule("with-respect-to-capitalized", `\bWith respect to\b`, "About"),
		newRule("with-respect-to", `\bwith respect to\b`, "about"),
		newRule("while-still-keeping-capitalized", `\bWhile still keeping\b`, "While keeping"),
		newRule("while-still-keeping", `\bwhile still keeping\b`, "while keeping"),
		newRule("both-humans-and", `\bboth humans and\b`, "humans and"),
		newRule("in-order-to-capitalized", `\bIn order to\b`, "To"),
		newRule("in-order-to", `\bin order to\b`, "to"),
		newRule("utilize", `\butilize\b`, "use"),
		newRule("understandable-to", `\bunderstandable to\b`, "clear to"),
		newRule("easy-to-scan", `\beasy to scan\b`, "scannable"),
		newRule("concise-and-scannable", `\bconcise and scannable\b`, "concise, scannable"),
		newRule("unnecessary-filler-words", `\bunnecessary filler words\b`, "filler words"),
		newRule("to-keep-context-small", `\b[Tt]o keep context small, use\b`, "keep context small; use"),
		newRule("paths-like", `\bpaths like\b`, "paths"),
		newRule("commands-like", `\bcommands like\b`, "commands"),
	}
}
