name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  actions: write

concurrency:
  group: release-please-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger goreleaser
        if: ${{ steps.release.outputs.release_created }}
        run: gh workflow run goreleaser.yml -f tag=${{ steps.release.outputs.tag_name }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
